### ISSUE TITLE
First hash change

### ISSUE THREAD

**Issue by Yomguithereal** [christianalfoni/react-addressbar#2]
Hello @christianalfoni, I was wondering if there was maybe something weird with your components in cases where you want the hash to be set by props. It seems that the first time it is changed, it will allow it which should not happen while subsequent changes will revert to the original correct prop.

_Example_

``` jsx
class App extends Component {
  onHashChange(url) {
    const hash = location.hash;
    console.log(hash);
  }

  render() {
    return (
      <div id="main">
        <Addressbar onlyHash={true}
                    onChange={this.onHashChange}
                    value={this.props.url} />
        Hello World!
      </div>
    );
  }
}

render(<App url="/#/one" />, ...);

// If I manually change the url to /#/two, it will switch whereas it should not
// Then if I manually change the url to /#/three it correctly goes to /#/one
```

**Comment by christianalfoni** [comment]
Hi @Yomguithereal and thanks for taking the time to test and create the issue :-)

I believe I have fixed this issue now. Could you verify?

**Comment by christianalfoni** [comment]
Hm, no, I think there is still something wrong... hmf, this is so freakin hard to handle, think I have to set up some really smart testing somehow. Not sure how though

**Comment by Yomguithereal** [comment]
@christianalfoni, I think the problem occurs only when setting `onlyChange` to `true`.

**Comment by christianalfoni** [comment]
Hm, the problem is that prevention of urls replaces current url with previous. Problem is that you might async set the url after preventing... which causes a flicker. But hm... that is a Cerebral issue, wait a minute here... lets see :-)

**Comment by Yomguithereal** [comment]
Url changes have always been black voodoo magic :-)

**Comment by christianalfoni** [comment]
Haha, yeah, that is what I am hoping to fix with this project. And I think I just cracked it. I was confused by cerebral-router doing async stuff. So problem was there, not in this project :-)

Just have to release a new version as I forgot to remove some logging

**Comment by christianalfoni** [comment]
Okay Mr., try it now :-)

**Comment by christianalfoni** [comment]
No, wait, what the fudge...

**Comment by christianalfoni** [comment]
ah. no, yes it works :)

**Comment by christianalfoni** [comment]
No wait, it does not... ush! two secs

**Comment by Yomguithereal** [comment]
What does work now?

**Comment by christianalfoni** [comment]
ah, no, it works... hehe... there is a bug in Chrome. Sometimes the url displays '/#/' but it is the previous url in location.href... but another refresh fixes that

**Comment by christianalfoni** [comment]
You have any experience with like "browser tests"? Isn't there a tool like selenium or something? Running live in the browser? Is there a service for that maybe? I can not see any other way to test this lib.

**Comment by Yomguithereal** [comment]
So should I try again? (Need to point on the github master of `addressbar`?)

**Comment by christianalfoni** [comment]
I have published a new package, so just install react-addressbar again :)

**Comment by Yomguithereal** [comment]
You can test in phantomjs, I can point you towards a repository doing this if you want.

**Comment by christianalfoni** [comment]
Ah, I have been using phantomJS before, but does it handle pop/hash events etc.? I suppose it should

**Comment by christianalfoni** [comment]
I can try that first, thanks :)

**Comment by Yomguithereal** [comment]
Check [this](https://github.com/jacomyal/baobab-router) for instance, using `mocha-phantomjs`. I guess phantomJS handle this quite well actually.

**Comment by christianalfoni** [comment]
Ah, cool, thanks again! Will set this up as soon as I get some time on my hands.

**Comment by Yomguithereal** [comment]
This is quite heavy to setup though, plan some time indeed.

**Comment by Yomguithereal** [comment]
Anyway, thanks for the fix @christianalfoni. Will try that asap.

**Comment by christianalfoni** [comment]
Actually I will go solo from October 1. Working on my own project, Cerebral and open source in general. Waiting for reply on an application for funding now. Really exciting stuff. Will be a huge party tweet if everything works out ;-)
