### ISSUE TITLE
Back and forward not working after link followed

### ISSUE THREAD

**Issue by mushishi78** [christianalfoni/react-addressbar#3]
Sorry about the confusing feedback from the issue on the other repository. Contrary to what I reported, I had not replicated or solved the problem as it has nothing to do with ES6.

I've created a new repository, [react-addressbar-test](https://github.com/mushishi78/react-addressbar-test), which is simply the example code given in the README of this project with the slight change that the current url in the state, `this.state.url`, is displayed in the heading to make it clear when the state is updated.

Steps to reproduce:
1. `npm start`
2. Navigate to http://127.0.0.1:8080
3. Click foo
4. Click Back

Then the address bar changes but the displayed state doesn't. It'd be cool if you could try this out to see if you get the same thing.

**Comment by christianalfoni** [comment]
Looking into it now! Thanks for really good reporting :-)

**Comment by christianalfoni** [comment]
Hi @mushishi78!

I found a couple of issues and they are fixed :-) Would you mind trying it out again?

Btw, addressbar gives full url on changes, so consider doing this:

``` js
  onChange: function (url) {
    this.setState({
      url: url.replace(location.origin, '')
    });
  },
```

**Comment by mushishi78** [comment]
I'm afraid to say that it seems to have got worse, not better, Now the back and forward buttons don't update the state at all, irrespective of whether any links have been used.

**Comment by christianalfoni** [comment]
Which version of addressbar is it installed? I went on to a different issue which required some changes, so might be on the wrong version. Latest is "0.1.20"

**Comment by mushishi78** [comment]
Yeah, 0.1.20

**Comment by christianalfoni** [comment]
Ah, sorry, I was working on the hash version... okay, let me look into it. I will have to set up some phantomJS testing for this stuff. It is getting pretty complex :)

**Comment by christianalfoni** [comment]
ah, Was just a minor thing. Just referenced a function, not calling it. Creating new package now

**Comment by christianalfoni** [comment]
Okay, 0.1.21, please try again :-)

**Comment by mushishi78** [comment]
That seems to working. Thanks!

**Comment by christianalfoni** [comment]
Great, thanks for trying it out! Let me know if there are any more issues!
