### ISSUE TITLE
Peer Dependency

### ISSUE THREAD

**Issue by Yomguithereal** [christianalfoni/react-addressbar#5]
Hello @christianalfoni. I don't know why but it seems you peer dependency declaration does not work well with `react@0.14.0-beta3`. However, your declaration seems fine so I am a bit puzzled.

**Comment by christianalfoni** [comment]
Tried deleting node_modules folder and install everything again? If any changes has been done sometimes it just messes up everything and need to install from scratch :-)

**Comment by Yomguithereal** [comment]
Unfortunately this does not work. Maybe it's due to a particular version of npm but it seems that `peerDependencies` using not "standard" semver version such as those prefixed with "-beta" etc. mess the whole thing.

**Comment by Yomguithereal** [comment]
Anyway, your current peer dep on React is `0.13` and preventing from using it correctly with the lastest RC.

**Comment by christianalfoni** [comment]
Ah, yeah, I got that issue on `cerebral-react` too, hm, okay, let me add the latest release candidate to the package.json file

**Comment by Yomguithereal** [comment]
Or just drop the peer dep and forget about all this turmoil :) ?

**Comment by christianalfoni** [comment]
Hehe... yeah, it would be kinda weird not to specifically add react to the project dependencies :) Okay, I will do that for both projects then

**Comment by christianalfoni** [comment]
Okay, latest version has no peer dependencies!
